### ISSUE TITLE
script incorrectly imports itunes phono copyrights holder as release labels

### ISSUE THREAD

**Issue by fmera** [dufferzafar/Userscripts#13] opened 2017-08-04 06:05 UTC
this script: https://github.com/dufferzafar/Userscripts/blob/master/MB-Import-From-iTunes.user.js seems to mistakenly import itunes ℗ copyrights holders data as release labels, so editors who use this script are (probably unknowingly) adding wrong data to digital releases.

to my best knowledge, itunes never actually offers release label info.

could you review the script accordingly to correct this error, thks.

**Comment by augustjanse** [comment] 2017-08-04 06:38
Duplicate of #4, see the discussion there. Not that it was conclusive, but check out my arguments for keeping it.

**Comment by dufferzafar** [comment] 2017-08-04 07:02
Hey! @augustjanse Would you mind if I gave you collaborator rights to this repo?

**Comment by augustjanse** [comment] 2017-08-04 07:59
I'm honored! Thanks 🙂

I'll close this to reopen the other issue.

**Closed by augustjanse** 2017-08-04 07:59 UTC
