### ISSUE TITLE
iTunes sound copyright field does not belong in the MusicBrainz release label

### ISSUE THREAD

**Issue by dukeyin** [dufferzafar/Userscripts#4] opened 2015-02-25 03:57 UTC
iTunes doesn't have labels at all.  (Copyright holders are not MusicBrainz labels.)

For example, compare the exact same release across 3 different digital download stores:
https://itunes.apple.com/jp/album/id420620236
http://mora.jp/package/43000002/ANICD-14145/
http://www.amazon.co.jp/dp/B009B4ZPBK/

As a result, this code should be removed:
https://github.com/dufferzafar/Userscripts/blob/master/MB-Import-From-iTunes.user.js#L94-L97

**Comment by dufferzafar** [comment] 2015-02-25 18:16
Thanks for reporting, but sorry as I don't really get exactly what you're pointing at (as I didn't get the japanese ones). Could you please give links to some English releases? Also, that code wasn't written by me so I'll first discuss in #musicbrainz-devel

**Comment by dukeyin** [comment] 2015-02-25 19:23
Japan has nothing to do with the issue, so yes - here's a US example:

https://itunes.apple.com/us/album/god-says-no/id362438
http://www.amazon.com/gp/product/B001NYTSOQ/
The label on Amazon Digital Music is A&M, but the company holding the copyrights is "Interscope Geffen A&M" on both stores.

(The Japan example is supposed to show that the label is "cutting edge" but the copyright holder is "AVEX ENTERTAINMENT INC.")

**Comment by augustjanse** [comment] 2015-07-22 17:09
I find it helpful. Obviously, something like Universal isn't right most of the time, but a lot of times the actual label is in there, to the degree digital media releases have labels at all. I don't know if there's any discussion on that.

Example: [This release](https://itunes.apple.com/us/album/dubbel-margarita-single/id966622948), confirmed by [the label](http://goldenbest.se/releaser/).

**Comment by dukeyin** [comment] 2015-07-23 02:58
I think typically, you don't want to proliferate software with bad default settings.

It's way more common in the iTunes music store for the name of the company holding the music copyrights to *not* have the same name as the thing MusicBrainz voters want to see in the release label.

**Comment by augustjanse** [comment] 2015-07-23 08:53
You're probably right in principle. But from a pragmatic perspective, the pros outweigh the cons for my workflow. It's easier to check the textbox for anything that looks like an actual label than it is checking the iTunes page. I would mind only if the label was selected automatically. But I can see how it would be a problem if people were adding copyright holders mistakenly.

**Comment by dufferzafar** [comment] 2017-06-09 06:16
Closing because I can't figure out what needs to be done in this case.

**Comment by augustjanse** [comment] 2017-06-12 07:26
It should probably be noted that this data fits perfectly into the [copyright relationship](https://beta.musicbrainz.org/relationship/2ed5a497-4f85-4b3f-831e-d341ad28c544) (as well as fitting or not as label data), but maybe it isn't possible to add relationships while adding releases.

**Comment by fmera** [comment] 2017-08-04 07:03
thks for the redirect to this thread. but i disagree with the suggestion that the pros outweigh the cons when conflating two very different things: copyrights vs. release labels. one is _not_ the other, and if any editor were to manually submit such an edit confusing between the two, i would certainly object to it. if you are unable to properly transfer the data from itunes to where it _should_ belong, then my suggestion is to suppress that copyrights data from being imported at all.

as the script automates this, editors adding wrong release data can truthfully claim it is not their doing or intention, and editors like myself would just have to fix these errors continually as long as those editors continue to use the script. that to me is not a good arrangement.

**Comment by augustjanse** [comment] 2017-08-04 07:59
I can't say I get a lot of useful data from the auto-fill. But I will state that although copyrights and release labels are very different things, it definitely does happen that one can be found through the other. (On the other hand, I'm not entirely sure that's the case for my earlier example, since it's associated with the label but doesn't have the imprint. I don't know, labels are complicated.)

Another point is that with the redesign, the copyright info isn't visible on the iTunes page anymore. So for the cases where something useful can be found there, it will now be nowhere to be seen at all. This could be fixed pretty easily by adding a visible string to the iTunes page in the script.

Well, my argument for keeping it was the pragmatic one. If you feel like it's resulting in more work than it's saving, we should probably fix it. How much extra work would you estimate this is giving you? I will reopen this if @dufferzafar doesn't mind.

**Comment by fmera** [comment] 2017-08-04 09:09
> But I will state that although copyrights and release labels are very different things, it definitely does happen that one can be found through the other.

not exactly true. a larger record company could have multiple divisions => label  groups => imprints under them, so the exact label to use for a particular release by a particular artist in a particular country _cannot_ be deduced from just copyrights data alone. only in cases of small or independent record companies would we sometimes _dispense_ with creating separate entities for the company and its label(imprint), particularly when both are named exactly the same way. but strictly speaking, aside from those exceptions we make, release labels should refer to _imprints_, and copyrights are held by legal corporations like companies, or even by persons.

> I don't know, labels are complicated.

_this is very true_. which is why i'm trying to draw attention to this issue, to resolve what i see as a flaw in the script. the misuse of record companies as release labels is a very big problem in musicbrainz, despite the many label comments we add to them to deter editors from doing so. so we don't want to add to the problem by having any scripts (which for one thing, probably don't real label comments!) contribute even more errors.

> the copyright info isn't visible on the iTunes page anymore.

was initially the case, but i'm beginning to see that info reintroduced into itunes release pages now.

> How much extra work would you estimate this is giving you?

from my own observation, i would say the script is fairly popular with editors, as i encounter several every day based on just labels i'm subscribed to.

**Comment by augustjanse** [comment] 2017-08-10 15:17
I knew you would get me for admitting labels are complicated 😉 Yes, small and indie labels are what I'm referring to, as in the very old example above. Thanks for the explanation of making exceptions, that makes sense. There's more discussion to be had concerning labels, but maybe not here.

Anyway, I'll submit a pull request for this ASAP.

**Closed** 2017-08-11 06:57 UTC

**Comment by AzoresOne** [comment] 2017-08-11 23:30
Hi,
Mind if I add my 2 cents?
I agree with fmera. On the other hand, at least iTunes supplies copyright info to add to release ARs ;) and it's a starting point to figuring out the correct label.
Google Play carries "almost" every release iTunes has (and has superior coverart, ie, less compressed), so when I add a release via iTunes via this script I head over to Google Play to check if they have the same release and most of the times they have the correct label (at bottom of page).
I take advantage of this issue to also ask (something I've been wanting to ask for a long time), when are you coming out with a GooglePlay import script? That would be awesome. They also have releases iTunes doesn't carry. Thanks.

**Comment by dufferzafar** [comment] 2017-08-12 04:24
@AzoresOne Can you provide some links of releases where Google Play Music has more info than iTunes?

Creating new import scripts isn't hard. Maintaining them is.
